server:
  port: 8086
  servlet:
    context-path: /gateway

#服务名
spring:
  application:
    name: gateway

#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   # 指定注册中心的地址
  instance:
    preferIpAddress: true

logging:
  level:
    com.czl.gateway: debug

zuul:
  routes:
    #权限
    privileges.path: /privileges/**
    privileges.serviceId: privileges
    privileges.strip-prefix: false
    #业务
    business.path: /business/**
    business.serviceId: business
    business.strip-prefix: false


